### ISSUE TITLE
Mechanism for revocation of a published sample result

### ISSUE THREAD

**Issue by gwsuperfan** [swimdrinkfish/opendata#2]
I think we need to add a mechanism to the standard to revoke a published sample result if it is discovered after-the-fact that a result is not valid due to an issue like malfunctioning/miscalibrated test equipment, improper collection technique that may have resulted in contamination, or some other issue.

**Comment by simplepanda** [comment]
These are good points. Just in conversation with @krystyntully here at SDFC the notion of samples being revoked without replacement is absolutely a condition that both can and HAS occurred in our day to day work.

I'm going to look at the best way to incorporate this into a final standard in terms of making some of the field structure optional; the issue would be the best approach to do so under something less than draft-07 of JSON-Schema (which adds if/else syntax).

**Comment by gabrielleswimguide** [comment]
A revokes object has been added as a water quality sample object. 

Revocation: A record issued in this standard can indicate that a previously issued record has been effectively "revoked". This is useful in instances where a publishing entity or organization is correcting previously issued record data, or is issuing new record data using more precise/accurate measurement methods. For example, a record issued using a predictive modelling method and be revoked by a second record when laboratory sample data becomes available.

Please note that it is considered a violation of the standard to revoke a GUID from another organization. The reverse FQDN portion of the original record and the revoking record should match before an entity or organization processing ingested records should consider the revocation valid. The validation schema makes no direct attempt to prevent cross-organization revocation from occurring, but consuming entities or organization are encouraged to account for this prohibition when processing ingested records.

The reference array allows for sample/s related to the revocation to be referenced directly. 

For more info see the [Sample Result Revocation and Referencing in the Reference document](https://github.com/swimdrinkfish/opendata/blob/master/v1.0/REFERENCE.md)

Closing this issue.
