### ISSUE TITLE
Multiple Samples

### ISSUE THREAD

**Issue by RobotGrrl** [swimdrinkfish/opendata#3]
For future extendability, it might be beneficial for sample to be an array (to have multiple samples). Some locations may take numerous samples and search for different substances. For example, extending the use to include a turbidity reading. 

Example snippet:

```
"substance": "clarity",
"method": "1337_turbidity_disk",
"units": "m",
"result": 1.5
```

**Comment by gabrielleswimguide** [comment]
We had much discussion on this topic. The consensus was that each GUID represents the sample and results from a single substance. However, other GUIDs can be referenced. So, if multiple substances were sampled there is the option to reference the other substances' GUID (sample and results) in "other object reference". The data standard is intended for recreational water quality data from persistent and predicted models (fecal indicator bacteria, cyanobacteria, cyanotoxins). However, you could adapt for environmental parameters.
