### ISSUE TITLE
Advisory Standards

### ISSUE THREAD

**Issue by RobotGrrl** [swimdrinkfish/opendata#4]
One of the fields in the data is an advisory, which is a boolean based on the local water quality standard.

It's not exactly clear to me how this will be determined — would it be done by the user uploading the data? Will there also be an open data specification for the local water quality standards by the cities / municipalities?

**Comment by gwsuperfan** [comment]
Yes, the determination would be done by the user/entity that is publishing the data. 

I'm unaware of a plan for a data specification for local water quality standards.

**Comment by simplepanda** [comment]
We had some discussion about this when we were initially kicking the spec ideas around. It seems like sharing a definition of the local water quality standard would be a fairly major undertaking. I think the general consensus was that it would be pretty satisfactory for the publisher of the record to simply indicate yes/no if the record passes or fails the local standard.

Perhaps having an optional URL field to link to a definition of the local standard in a human readable way? Not sure if that would be necessary though. @gabrielleswimguide would definitely have some opinions on this, I'm sure.

**Comment by gabrielleswimguide** [comment]
To be clear, not all water quality monitoring bodies have the authority to issue an advisory. Since advisories can only be issues by a recognized authority, such as an environmental health officer, we can consider adding a mandatory string to identify who issued the advisory. 
The description string should cover the nature of the advisory (ie. exceeds local rwq criteria). I'm in favour of adding a description of the local criteria. URL could work.

**Comment by simplepanda** [comment]
Circling back on this - it feels like the description field of the advisory object would be sufficient to indicate any sort of descriptive element, no?

```
"advisory": {
	"issued": true,
	"description": "This advisory has been issued as this sample has exceeded the Ontario recreational water quality standards."
},
```

These "description" field could be anything the record issuer chose, including a link to their own website or documentation outlining the standard/policy under which the advisory was issued. Is that enough?

**Comment by gabrielleswimguide** [comment]
Confirming that the "description" field can be used to describe the nature of the advisory, include the local rwq criteria, and includes ability for the record issuer to include a link to their own website, or docs outlining standards/protocols/policies/fed recommendations under which the advisory was issued.
