### ISSUE TITLE
Additional Method Codes welcome

### ISSUE THREAD

**Issue by gabrielleswimguide** [swimdrinkfish/opendata#5]
When we created the method code list for methods used to enumerate sample results we anticipated that, as new methods become available, the list would be updated. We invite everyone to review the list of methods and to contribute any we may have missed. 
For example, we recently added two qPCR methods for E.coli: the EPA's draft Method C, and BioGX

**Comment by simplepanda** [comment]
Closed in order to allow people to open fresh tasks as needed to accomplish any additions to future standards. People already seem to be taking this approach. The primary project README.md could be updated to indicate issues should be opened when changes of this nature are desired.
