### ISSUE TITLE
Addition of method code "unknown"

### ISSUE THREAD

**Issue by gabrielleswimguide** [swimdrinkfish/opendata#7]
Method code is a string enumeration value indicating the method code that was used to enumerate the sample result number. This method code should correspond to a method used to enumerate the sampled substance. For more information about the valid method codes, please see “Appendix 1 - Method Codes” in reference doc. 

Suggest addition of method code "unknown/not provided" to the list of method codes. 
"Unknown/not provided" will allow for data where the sample analysis method was not provided.

**Comment by simplepanda** [comment]
Added "unknown" and "other" to v1.0.1 to handle edge cases.

Closed.
